### ISSUE TITLE
EOFError: read() didn't return enough bytes

### ISSUE THREAD

**Issue by wunderlife** [zqbai-jeremy/INORig#12]
I run demo.py but it seems there is size error with Exp_Pca.bin.

Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    model = init_model(checkpoint_path)
  File "demo.py", line 14, in init_model
    model = INORig(opt_step_size=1e-2)
  File "/home/dcrc/jh/INORig/networks/sub_nets.py", line 2179, in __init__
    self.opt_layer = NRMVSOptimization(opt_step_size=opt_step_size, MM_base_dir=MM_base_dir)
  File "/home/dcrc/jh/INORig/networks/sub_nets.py", line 1332, in __init__
    self.bfm = bfm_utils.load_3DMM(MM_base_dir)
  File "/home/dcrc/jh/INORig/data/BFM/utils.py", line 105, in load_3DMM
    bfm.model['expPC'], bfm.model['expEV'] = LoadExpBasis()
  File "/home/dcrc/jh/INORig/data/BFM/utils.py", line 61, in LoadExpBasis
    expPC.fromfile(Expbin, 3 * exp_dim[0] * n_vertex)
EOFError: read() didn't return enough bytes

How do I fix?

I check that exp_dim[0] equals to 79

**Comment by zqbai-jeremy** [comment]
Did you change any code? Look like "expPC.fromfile(Expbin, 3 * exp_dim[0] * n_vertex)" is in line 57. BTW, I did not remember I faced this error before.

**Comment by wunderlife** [comment]
I didn't change the code.
